title: WEBGUARDS News
description: Blog für Gründer
baseurl: ""
url: "https://news.webguards.de"
markdown: kramdown
theme: minima
permalink: /blog/:title/

plugins:
  - jekyll-feed

author:
  name: WEBGUARDS
  email: post@webguards.de
