title: WEBGUARDS News
description: Blog für Gründer – Prozesse, Automation und Sicherheit
url: "https://news.webguards.de"
baseurl: ""

markdown: kramdown
plugins:
  - jekyll-feed

author:
  name: WEBGUARDS
  email: post@webguards.de

excerpt_separator: "\n\n"
