name: Build Jekyll Site

on:
  push:
    branches:
      - main

jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Starting"
      - uses: actions/checkout@v4
      - run: echo "Checked out"
