name: Build Jekyll Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Ruby and build
        run: |
          apt-get update
          apt-get install -y ruby-full build-essential
          cd ${{ github.workspace }}
          gem install bundler jekyll
          bundle install
          bundle exec jekyll build
      
      - uses: actions/upload-pages-artifact@v2
        with:
          path: _site

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
    steps:
      - uses: actions/deploy-pages@v2
