name: Build Jekyll Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Starting build"
      - run: apt-get update && apt-get install -y ruby-full build-essential
      - run: gem install bundler jekyll
